### ISSUE TITLE
Create Velocity Over Time Plot Prototype

### ISSUE THREAD

**Issue by jrg94** [jrg94/data-viz-term-project#9]
Let's plot some dynamics!

**Comment by wustep** [comment]
re: #20 

---

This looks like a good start! Def some more exploration can be done here. Maybe this is sufficient for the prototype (after fixing bug).

Ideas: 
- Try scatter plot instead of lines, don't sum velocity. 
  - Add single average line to scatter plot. Plot a point that represents the average velocity of every note played at every time. Connect these dots smoothly for the line.

Improvement: 
- Add the note itself to the data so we can add it to the tooltip later. We might also want to add track number to the data too, and add these to tooltips in master/this plot. 

Bug: 
- Doesn't show second MIDI file with proper color

**Comment by jrg94** [comment]
Sounds good. I only summed them because if velocity has anything to do with volume I can't imagine that more than one sound would be quieter. Also, summing is easier haha.

**Comment by wustep** [comment]
Closing this for now, moving improvements to new issue!

Also, bug noted above was fixed.
